=== MaksymMedvedchuk/Weather/target/Weather-1.0-SNAPSHOT/WEB-INF/classes/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/year"
            elementFormDefault="qualified" xmlns="http://www.example.com/year">
    <xsd:element name="year" type="year"/>

    <xsd:complexType name="year">
        <xsd:sequence>
            <xsd:element name="month" type="month" maxOccurs="12" minOccurs="12"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="month">
        <xsd:sequence>
            <xsd:element name="monthName" type="monthName"/>
            <xsd:element name="day" type="day" minOccurs="28" maxOccurs="31">
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="monthName">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="February"/>
            <xsd:enumeration value="March"/>
            <xsd:enumeration value="April"/>
            <xsd:enumeration value="May"/>
            <xsd:enumeration value="June"/>
            <xsd:enumeration value="July"/>
            <xsd:enumeration value="August"/>
            <xsd:enumeration value="September"/>
            <xsd:enumeration value="October"/>
            <xsd:enumeration value="November"/>
            <xsd:enumeration value="December"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="day">
        <xsd:sequence>
            <xsd:element name="dayNumber">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="31"/>
                        <xsd:minInclusive value="1"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="temperature">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="30"/>
                        <xsd:minInclusive value="-30"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== MaksymMedvedchuk/Weather/out/artifacts/Weather_war_exploded/WEB-INF/classes/schema.xml
<?xml version="1.0" encoding="utf-8"?>
<year xmlns="http://www.example.com/year" xsi:schemaLocation="http://www.example.com/year schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <month>
    <monthName>March</monthName>
    <day>
      <dayNumber>5</dayNumber>
      <temperature>13</temperature>
    </day>
    <day>
      <dayNumber>13</dayNumber>
      <temperature>-16</temperature>
    </day>
    <day>
      <dayNumber>10</dayNumber>
      <temperature>-8</temperature>
    </day>
    <day>
      <dayNumber>28</dayNumber>
      <temperature>4</temperature>
    </day>
    <day>
      <dayNumber>31</dayNumber>
      <temperature>21</temperature>
    </day>
    <day>
      <dayNumber>27</dayNumber>
      <temperature>14</temperature>
    </day>
    <day>
      <dayNumber>7</dayNumber>
      <temperature>-21</temperature>
    </day>
    <day>
      <dayNumber>13</dayNumber>
      <temperature>-1</temperature>
    </day>
    <day>
      <dayNumber>23</dayNumber>
      <temperature>7</temperature>
    </day>
    <day>
      <dayNumber>30</dayNumber>
      <temperature>-13</temperature>
    </day>
    <day>
      <dayNumber>15</dayNumber>
      <temperature>-20</temperature>
    </day>
    <day>
      <dayNumber>23</dayNumber>
      <temperature>-15</temperature>
    </day>
    <day>
      <dayNumber>20</dayNumber>
      <temperature>-28</temperature>
    </day>
    <day>
      <dayNumber>4</dayNumber>
      <temperature>23</temperature>
    </day>
    <day>
      <dayNumber>18</dayNumber>
      <temperature>-26</temperature>
    </day>
    <day>
      <dayNumber>6</dayNumber>
      <temperature>5</temperature>
    </day>
    <day>
      <dayNumber>11</dayNumber>
      <temperature>-29</temperature>
    </day>
    <day>
      <dayNumber>20</dayNumber>
      <temperature>-2</temperature>
    </day>
    <day>
      <dayNumber>29</dayNumber>
      <temperature>21</temperature>
    </day>
    <day>
      <dayNumber>19</dayNumber>
      <temperature>-7</temperature>
    </day>
    <day>
      <dayNumber>23</dayNumber>
      <temperature>21</temperature>
    </day>
    <day>
      <dayNumber>22</dayNumber>
      <temperature>-12</temperature>
    </day>
    <day>
      <dayNumber>29</dayNumber>
      <temperature>16</temperature>
    </day>
    <day>
      <dayNumber>5</dayNumber>
      <temperature>27</temperature>
    </day>
    <day>
      <dayNumber>3</dayNumber>
      <temperature>25</temperature>
    </day>
    <day>
      <dayNumber>15</dayNumber>
      <temperature>24</temperature>
    </day>
    <day>
      <dayNumber>12</dayNumber>
      <temperature>-4</temperature>
    </day>
    <day>
      <dayNumber>20</dayNumber>
      <temperature>21</temperature>
    </day>
    <day>
      <dayNumber>6</dayNumber>
      <temperature>25</temperature>
    </day>
    <day>
      <dayNumber>2</dayNumber>
      <temperature>10</temperature>
    </day>
  </month>
  <month>
    <monthName>June</monthName>
    <day>
      <dayNumber>1</dayNumber>
      <temperature>-25</temperature>
    </day>
    <day>
      <dayNumber>25</dayNumber>
      <temperature>-12</temperature>
    </day>
    <day>
      <dayNumber>16</dayNumber>
      <temperature>-21</temperature>
    </day>
    <day>
      <dayNumber>16</dayNumber>
      <temperature>-5</temperature>
    </day>
    <day>
      <dayNumber>10</dayNumber>
      <temperature>-11</temperature>
    </day>
    <day>
      <dayNumber>5</dayNumber>
      <temperature>15</temperature>
    </day>
    <day>
      <dayNumber>17</dayNumber>
      <temperature>14</temperature>
    </day>
    <day>
      <dayNumber>27</dayNumber>
      <temperature>-13</temperature>
    </day>
    <day>
      <dayNumber>18</dayNumber>
      <temperature>25</temperature>
    </day>
    <day>
      <dayNumber>19</dayNumber>
      <temperature>-18</temperature>
    </day>
    <day>
      <dayNumber>9</dayNumber>
      <temperature>5</temperature>
    </day>
    <day>
      <dayNumber>6</dayNumber>
      <temperature>-29</temperature>
    </day>
    <day>
      <dayNumber>18</dayNumber>
      <temperature>-26</temperature>
    </day>
    <day>
      <dayNumber>21</dayNumber>
      <temperature>-7</temperature>
    </day>
    <day>
      <dayNumber>29</dayNumber>
      <temperature>27</temperature>
    </day>
    <day>
      <dayNumber>27</dayNumber>
      <temperature>12</temperature>
    </day>
    <day>
      <dayNumber>30</dayNumber>
      <temperature>28</temperature>
    </day>
    <day>
      <dayNumber>4</dayNumber>
      <temperature>-10</temperature>
    </day>
    <day>
      <dayNumber>14</dayNumber>
      <temperature>-14</temperature>
    </day>
    <day>
      <dayNumber>22</dayNumber>
      <temperature>26</temperature>
    </day>
    <day>
      <dayNumber>27</dayNumber>
      <temperature>-5</temperature>
    </day>
    <day>
      <dayNumber>9</dayNumber>
      <temperature>4</temperature>
    </day>
    <day>
      <dayNumber>9</dayNumber>
      <temperature>-18</temperature>
    </day>
    <day>
      <dayNumber>17</dayNumber>
      <temperature>-25</temperature>
    </day>
    <day>
      <dayNumber>14</dayNumber>
      <temperature>-23</temperature>
    </day>
    <day>
      <dayNumber>13</dayNumber>
      <temperature>-4</temperature>
    </day>
    <day>
      <dayNumber>16</dayNumber>
      <temperature>10</temperature>
    </day>
    <day>
      <dayNumber>6</dayNumber>
      <temperature>10</temperature>
    </day>
    <day>
      <dayNumber>20</dayNumber>
      <temperature>11</temperature>
    </day>
    <day>
      <dayNumber>22</dayNumber>
      <temperature>-15</temperature>
    </day>
  </month>
  <month>
    <monthName>May</monthName>
    <day>
      <dayNumber>16</dayNumber>
      <temperature>-21</temperature>
    </day>
    <day>
      <dayNumber>19</dayNumber>
      <temperature>28</temperature>
    </day>
    <day>
      <dayNumber>9</dayNumber>
      <temperature>26</temperature>
    </day>
    <day>
      <dayNumber>28</dayNumber>
      <temperature>-3</temperature>
    </day>
    <day>
      <dayNumber>23</dayNumber>
      <temperature>1</temperature>
    </day>
    <day>
      <dayNumber>3</dayNumber>
      <temperature>23</temperature>
    </day>
    <day>
      <dayNumber>7</dayNumber>
      <temperature>8</temperature>
    </day>
    <day>
      <dayNumber>16</dayNumber>
      <temperature>-4</temperature>
    </day>
    <day>
      <dayNumber>19</dayNumber>
      <temperature>-25</temperature>
    </day>
    <day>
      <dayNumber>14</dayNumber>
      <temperature>-12</temperature>
    </day>
    <day>
      <dayNumber>19</dayNumber>
      <temperature>-29</temperature>
    </day>
    <day>
      <dayNumber>25</dayNumber>
      <temperature>-20</temperature>
    </day>
    <day>
      <dayNumber>5</dayNumber>
      <temperature>-14</temperature>
    </day>
    <day>
      <dayNumber>1</dayNumber>
      <temperature>18</temperature>
    </day>
    <day>
      <dayNumber>14</dayNumber>
      <temperature>14</temperature>
    </day>
    <day>
      <dayNumber>1</dayNumber>
      <temperature>-27</temperature>
    </day>
    <day>
      <dayNumber>21</dayNumber>
      <temperature>-21</temperature>
    </day>
    <day>
      <dayNumber>12</dayNumber>
      <temperature>-4</temperature>
    </day>
    <day>
      <dayNumber>11</dayNumber>
      <temperature>4</temperature>
    </day>
    <day>
      <dayNumber>14</dayNumber>
      <temperature>12</temperature>
    </day>
    <day>
      <dayNumber>25</dayNumber>
      <temperature>27</temperature>
    </day>
    <day>
      <dayNumber>25</dayNumber>
      <temperature>-16</temperature>
    </day>
    <day>
      <dayNumber>6</dayNumber>
      <temperature>-20</temperature>
    </day>
    <day>
      <dayNumber>30</dayNumber>
      <temperature>4</temperature>
    </day>
    <day>
      <dayNumber>24</dayNumber>
      <temperature>-27</temperature>
    </day>
    <day>
      <dayNumber>5</dayNumber>
      <temperature>25</temperature>
    </day>
    <day>
      <dayNumber>18</dayNumber>
      <temperature>1</temperature>
    </day>
    <day>
      <dayNumber>2</dayNumber>
      <temperature>13</temperature>
    </day>
    <day>
      <dayNumber>9</dayNumber>
      <temperature>-11</temperature>
    </day>
    <day>
      <dayNumber>7</dayNumber>
      <temperature>8</temperature>
    </day>
  </month>
  <month>
    <monthName>July</monthName>
    <day>
      <dayNumber>20</dayNumber>
      <temperature>-6</temperature>
    </day>
    <day>
      <dayNumber>19</dayNumber>
      <temperature>-17</temperature>
    </day>
    <day>
      <dayNumber>9</dayNumber>
      <temperature>-22</temperature>
    </day>
    <day>
      <dayNumber>24</dayNumber>
      <temperature>-3</temperature>
    </day>
    <day>
      <dayNumber>24</dayNumber>
      <temperature>12</temperature>
    </day>
    <day>
      <dayNumber>1</dayNumber>
      <temperature>-12</temperature>
    </day>
    <day>
      <dayNumber>21</dayNumber>
      <temperature>3</temperature>
    </day>
    <day>
      <dayNumber>15</dayNumber>
      <temperature>-13</temperature>
    </day>
    <day>
      <dayNumber>3</dayNumber>
      <temperature>20</temperature>
    </day>
    <day>
      <dayNumber>19</dayNumber>
      <temperature>19</temperature>
    </day>
    <day>
      <dayNumber>5</dayNumber>
      <temperature>-28</temperature>
    </day>
    <day>
      <dayNumber>24</dayNumber>
      <temperature>-3</temperature>
    </day>
    <day>
      <dayNumber>31</dayNumber>
      <temperature>-29</temperature>
    </day>
    <day>
      <dayNumber>10</dayNumber>
      <temperature>-11</temperature>
    </day>
    <day>
      <dayNumber>30</dayNumber>
      <temperature>14</temperature>
    </day>
    <day>
      <dayNumber>30</dayNumber>
      <temperature>-19</temperature>
    </day>
    <day>
      <dayNumber>1</dayNumber>
      <temperature>24</temperature>
    </day>
    <day>
      <dayNumber>8</dayNumber>
      <temperature>23</temperature>
